/*Crud BIBLIOTECA*/
ALTER TABLE telefonos ADD CONSTRAINT CH_TELEFONOS
CHECK (LENGTH(TRIM(TRANSLATE(telefono, '0123456789', ' '))) = 0);
ALTER TABLE bibliotecas ADD CONSTRAINT CH_BIBLIOTECA
CHECK (correo LIKE '%@%.%');

/**Crud Afiliado*/


ALTER TABLE afiliados ADD CONSTRAINT CH_AFILIADO0
CHECK (LENGTH(TRIM(TRANSLATE(codigo, '0123456789', ' '))) = 0);
ALTER TABLE afiliados ADD CONSTRAINT CH_AFILIADO1
CHECK (bloqueado IN (1 , 0));
ALTER TABLE afiliados ADD CONSTRAINT CH_AFILIADO2
CHECK (correo LIKE '%@%.%');
ALTER TABLE afiliados ADD CONSTRAINT CH_AFILIADO3
CHECK (tipo IN ('o' , 'p', 'n'));
ALTER TABLE intereses ADD CONSTRAINT CH_INTERES
CHECK (LENGTH(TRIM(TRANSLATE(palabra, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-', ' '))) = 0);
ALTER TABLE afiliados ADD CONSTRAINT CH_AFILIADO4
CHECK (LENGTH(TRIM(TRANSLATE(telefono, '0123456789', ' '))) = 0);
ALTER TABLE afiliados ADD CONSTRAINT CH_AFILIADO5
CHECK (LENGTH(TRIM(TRANSLATE(cedula, '0123456789', ' '))) = 0);
ALTER TABLE afiliados ADD CONSTRAINT CH_AFILIADO6
CHECK (LENGTH(TRIM(TRANSLATE(nombre, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ' '))) = 0);
ALTER TABLE afiliados_oro ADD CONSTRAINT CH_AFILIADO_ORO
CHECK (diasExtra >= 0);
ALTER TABLE afiliados_plata ADD CONSTRAINT CH_AFILIADO_PLATA
CHECK (diasExtra >= 0);
ALTER TABLE afiliados_normal ADD CONSTRAINT CH_AFILIADO_NORMAL
CHECK (diasExtra >= 0);

/*CRUD empleado*/
ALTER TABLE empleados ADD CONSTRAINT CH_EMPLEADO1
CHECK (correo LIKE '%@%.%');
ALTER TABLE empleados ADD CONSTRAINT CH_EMPLEADO2
CHECK (LENGTH(TRIM(TRANSLATE(telefono, '0123456789', ' '))) = 0);
ALTER TABLE empleados ADD CONSTRAINT CH_EMPLEADO3
CHECK (LENGTH(TRIM(TRANSLATE(cedula, '0123456789', ' '))) = 0);
ALTER TABLE empleados ADD CONSTRAINT CH_EMPLEADO4
CHECK (LENGTH(TRIM(TRANSLATE(nombre, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-', ' '))) = 0);
ALTER TABLE empleados ADD CONSTRAINT CH_EMPLEADO5
CHECK (salario >= 0);
ALTER TABLE empleados ADD CONSTRAINT CH_EMPLEADO6
CHECK (tipo IN ('b' , 'a', 's'));


/*CRUD libro*/
ALTER TABLE etiquetas ADD CONSTRAINT CH_ETIQUETA
CHECK (LENGTH(TRIM(TRANSLATE(palabra, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ' '))) = 0);
ALTER TABLE autores ADD CONSTRAINT CK_AUTOR1
CHECK (LENGTH(TRIM(TRANSLATE(nombre, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-.', ' '))) = 0);
ALTER TABLE libros ADD CONSTRAINT CH_LIBRO1
CHECK (precio >= 0);
ALTER TABLE libros ADD CONSTRAINT CH_LIBRO2
CHECK (diasPrestamo >= 0);
ALTER TABLE libros ADD CONSTRAINT CH_LIBRO3
CHECK (precioDiaDemora >= 0);
ALTER TABLE libros ADD CONSTRAINT CH_LIBRO4
CHECK (libre IN (1 , 0));
ALTER TABLE libros ADD CONSTRAINT CH_LIBRO5
CHECK (LENGTH(TRIM(TRANSLATE(SUBSTR(direccion,1,3), 'abcdefghijklmnopqrstuvwxyz', ' '))) = 0);
ALTER TABLE libros ADD CONSTRAINT CH_LIBRO6
CHECK (LENGTH(TRIM(TRANSLATE(SUBSTR(direccion,4,3), '0123456789', ' '))) = 0);

/*CRUD reserva*/

/*CRUD prestamo*/

/*CRUD multa*/
ALTER TABLE multas ADD CONSTRAINT CH_MULTA
CHECK (valor >= 0);
