CREATE OR REPLACE PACKAGE PC_PRESTAMO IS 
  PROCEDURE AD_PRESTAMO (xempleado IN VARCHAR, xlibro IN VARCHAR, xafiliado IN VARCHAR);
  PROCEDURE DEVOLVER_lIBRO (xempleado IN VARCHAR, xlibro IN VARCHAR);
  PROCEDURE RENOVAR_PRESTAMO (xcodigo IN VARCHAR);
END PC_PRESTAMO;
/
CREATE OR REPLACE PACKAGE PC_LIBROS IS
    PROCEDURE AD_LIBRO(nombrex IN VARCHAR, preciox IN NUMBER, diasPrestamox IN NUMBER, precioDiaDemorax IN NUMBER, editorialx  IN VARCHAR, bibliotecax IN VARCHAR, archivistax IN VARCHAR, direccionx IN VARCHAR);
    PROCEDURE MO_LIBRO_PRECIO (codigox IN VARCHAR, preciox IN NUMBER);
    PROCEDURE MO_LIBRO_DIAS (codigox IN VARCHAR, diasPrestamox IN NUMBER);
    PROCEDURE MO_LIBRO_PRECIO_DIA (codigox IN VARCHAR, precioDiaDemorax IN NUMBER);
    PROCEDURE MO_LIBRO_EDITORIAL (codigox IN VARCHAR, editorialx  IN VARCHAR);
    PROCEDURE MO_DIRECCION (codigox IN VARCHAR, direccionx  IN VARCHAR);
    PROCEDURE AD_CATEGORIA (codigox IN VARCHAR, categoriax IN VARCHAR);
    PROCEDURE AD_AUTOR (codigox IN VARCHAR, nombrex IN VARCHAR);
    PROCEDURE AD_ETIQUETA (codigox IN VARCHAR, palabrax IN VARCHAR);
    PROCEDURE MO_CATEGORIA (codigox IN VARCHAR, categoriax IN VARCHAR, ncategoriax IN VARCHAR);
    PROCEDURE MO_AUTOR (codigox IN VARCHAR, nombrex IN VARCHAR, nnombrex IN VARCHAR);
    PROCEDURE MO_ETIQUETA (codigox IN VARCHAR, palabrax IN VARCHAR, npalabrax IN VARCHAR);
    PROCEDURE DE_LIBRO (codigox IN VARCHAR);
    FUNCTION CO_EDITORIALES_BIBLIOTECA (bibliotecax IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION BUSCAR_LIBRO (nombrex IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION BUSCAR_LIBRO_BIBLIOTECA (nombrex IN VARCHAR, bibliotecax IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION BUSCAR_LIBROS_AUTOR (autorx IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION BUSCAR_LIBROS_ETIQUETA (etiquetax IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION CO_CATEGORIAS_BIBLIOTECA (bibliotecax IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION NUM_LIBROS_BIBLIOTECA (bibliotecax IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION CO_MAS_POPULARES RETURN SYS_REFCURSOR;
END PC_LIBROS; 
/
CREATE OR REPLACE PACKAGE PC_RESERVA IS 
  PROCEDURE AD_RESERVA (xlibro IN VARCHAR, xafiliado IN VARCHAR);
  PROCEDURE CANCELAR_RESERVA (xreserva IN NUMBER);
END PC_RESERVA;
/
CREATE OR REPLACE PACKAGE PCK_AFILIADO IS 
  PROCEDURE AD_AFILIADO (cedulax VARCHAR, nombrex VARCHAR, correox VARCHAR, telefonox VARCHAR, tipox VARCHAR);
  PROCEDURE MO_AFILIADO_NOM (codigox VARCHAR, nombrex VARCHAR);
  PROCEDURE MO_AFILIADO_COR (codigox VARCHAR, correox VARCHAR);
  PROCEDURE MO_AFILIADO_TEL (codigox VARCHAR, telefonox VARCHAR);
  PROCEDURE MO_AFILIADO_TIP (codigox VARCHAR, tipox VARCHAR);
  PROCEDURE DE_AFILIADO (codigox VARCHAR);
  FUNCTION CO_INTERESES (codigox IN VARCHAR)  RETURN SYS_REFCURSOR;
  FUNCTION CO_LIBROS_SACADOS (codigox IN VARCHAR)  RETURN SYS_REFCURSOR;
END;
/
CREATE OR REPLACE PACKAGE PC_RESERVASALON IS
  PROCEDURE reservar (afiliadox varchar, numSalonx number, bibliotecax varchar, bibliotecariox varchar, iniciox DATE, finx DATE);
  PROCEDURE pagar (reservax number);
  PROCEDURE modificarFechas (reservax number, iniciox DATE, finx DATE);
  PROCEDURE eliminarReserva (reservax number);
  FUNCTION consultarSalon (tipox varchar) RETURN SYS_REFCURSOR;
  FUNCTION consultarSalon (tipox varchar, bibliotecax varchar) RETURN SYS_REFCURSOR;
END;
