CREATE OR REPLACE PACKAGE PC_PRESTAMO IS 
  PROCEDURE AD_PRESTAMO (xempleado IN VARCHAR, xlibro IN VARCHAR, xafiliado IN VARCHAR);
  PROCEDURE DEVOLVER_lIBRO (xempleado IN VARCHAR, xlibro IN VARCHAR);
END PC_PRESTAMO;

CREATE OR REPLACE PACKAGE PC_LIBROS IS
    PROCEDURE AD_LIBRO(nombrex IN VARCHAR, preciox IN NUMBER, diasPrestamox IN NUMBER, precioDiaDemorax IN NUMBER, editorialx  IN VARCHAR, bibliotecax IN VARCHAR, archivistax IN VARCHAR, direccionx IN VARCHAR);
    PROCEDURE MO_LIBRO_PRECIO (codigox IN VARCHAR, preciox IN NUMBER);
    PROCEDURE MO_LIBRO_DIAS (codigox IN VARCHAR, diasPrestamox IN NUMBER);
    PROCEDURE MO_LIBRO_PRECIO_DIA (codigox IN VARCHAR, precioDiaDemorax IN NUMBER);
    PROCEDURE MO_LIBRO_EDITORIAL (codigox IN VARCHAR, editorialx  IN VARCHAR);
    PROCEDURE MO_DIRECCION (codigox IN VARCHAR, direccionx  IN VARCHAR);
    PROCEDURE AD_CATEGORIA (codigox IN VARCHAR, categoriax IN VARCHAR);
    PROCEDURE AD_AUTOR (codigox IN VARCHAR, nombrex IN VARCHAR);
    PROCEDURE AD_ETIQUETA (codigox IN VARCHAR, palabrax IN VARCHAR);
    PROCEDURE MO_CATEGORIA (codigox IN VARCHAR, categoriax IN VARCHAR, ncategoriax IN VARCHAR);
    PROCEDURE MO_AUTOR (codigox IN VARCHAR, nombrex IN VARCHAR, nnombrex IN VARCHAR);
    PROCEDURE MO_ETIQUETA (codigox IN VARCHAR, palabrax IN VARCHAR, npalabrax IN VARCHAR);
    PROCEDURE DE_CATEGORIA (codigox IN VARCHAR, categoriax IN VARCHAR);
    PROCEDURE DE_AUTOR (codigox IN VARCHAR, nombrex IN VARCHAR);
    PROCEDURE DE_ETIQUETA (codigox IN VARCHAR, palabrax IN VARCHAR);
    PROCEDURE DE_LIBRO (codigox IN VARCHAR);
    FUNCTION CO_EDITORIALES_BIBLIOTECA (bibliotecax IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION CO_LIBROS_BIBLIOTECA (nombrex IN VARCHAR, bibliotecax IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION CO_LIBRO_LIBRE (nombrex IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION CO_LIBRO_LIBRE_B (nombrex IN VARCHAR, bibliotecax IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION CO_LIBRO__LIBRE_A (autorx IN VARCHAR)  RETURN SYS_REFCURSOR;
    FUNCTION CO_LIBRO_LIBRE_E (etiquetax IN VARCHAR)  RETURN SYS_REFCURSOR;
END PC_LIBROS; 
