/*Crud BIBLIOTECA*/
ALTER TABLE telefonos ADD CONSTRAINT FK_TELEFONO_BIBLIOTECA
FOREIGN KEY (biblioteca) REFERENCES bibliotecas(nombre);
ALTER TABLE telefonos ADD CONSTRAINT CK_TELEFONOS_TEL
CHECK (LENGTH(TRIM(TRANSLATE(telefono, '0123456789', ' '))) = 0);

/*Crud Afiliado*/

ALTER TABLE afiliados_oro ADD CONSTRAINT FK_AFILIADO_ORO
FOREIGN KEY (afiliado) REFERENCES afiliados(codigo)
ON DELETE CASCADE;
ALTER TABLE afiliados_plata ADD CONSTRAINT FK_AFILIADO_PLATA
FOREIGN KEY (afiliado) REFERENCES afiliados(codigo)
ON DELETE CASCADE;
ALTER TABLE afiliados_normal ADD CONSTRAINT FK_AFILIADO_NORMAL
FOREIGN KEY (afiliado) REFERENCES afiliados(codigo)
ON DELETE CASCADE;
ALTER TABLE intereses ADD CONSTRAINT PK_INTERES
PRIMARY KEY (afiliado, palabra);
ALTER TABLE intereses ADD CONSTRAINT FK_INTERES
FOREIGN KEY (afiliado) REFERENCES afiliados(codigo)
ON DELETE CASCADE;

/*CRUD empleado*/

ALTER TABLE empleados ADD CONSTRAINT FK_EMPLEADO_BIBLIOTECA
FOREIGN KEY (biblioteca) REFERENCES bibliotecas(nombre);
ALTER TABLE archivistas ADD CONSTRAINT FK_ARCHIVISTA
FOREIGN KEY (empleado) REFERENCES empleados(codigo)
ON DELETE CASCADE;
ALTER TABLE bibliotecarios ADD CONSTRAINT FK_BIBLIOTECARIO
FOREIGN KEY (empleado) REFERENCES empleados(codigo)
ON DELETE CASCADE;
ALTER TABLE servicio_generales ADD CONSTRAINT FK_SERVICIOS
FOREIGN KEY (empleado) REFERENCES empleados(codigo)
ON DELETE CASCADE;

/*CRUD autores*/
ALTER TABLE autores ADD CONSTRAINT PK_AUTOR
PRIMARY KEY (codigo);

/*CRUD libro*/
ALTER TABLE etiquetas ADD CONSTRAINT PK_ETIQUETA
PRIMARY KEY (libro, palabra);
ALTER TABLE etiquetas ADD CONSTRAINT FK_ETIQUETA
FOREIGN KEY (libro) REFERENCES libros(codigo);
ALTER TABLE libros ADD CONSTRAINT FK_LIBRO_BIBLIOTECA
FOREIGN KEY (biblioteca) REFERENCES bibliotecas(nombre);
ALTER TABLE libros ADD CONSTRAINT FK_LIBRO_ARCHIVISTA
FOREIGN KEY (archivista) REFERENCES archivistas(empleado);
ALTER TABLE autoresLibros ADD CONSTRAINT FK_CODIGO_LIBRO
FOREIGN KEY (libro) REFERENCES libros(codigo);
ALTER TABLE autoresLibros ADD CONSTRAINT FK_CODIGO_AUTOR
FOREIGN KEY (autor) REFERENCES autores(codigo);
ALTER TABLE libros ADD CONSTRAINT UK_LIBROS
UNIQUE (direccion, biblioteca);

/*CRUD reserva*/
ALTER TABLE reservas ADD CONSTRAINT FK_RESERVA1
FOREIGN KEY (afiliado) REFERENCES afiliados(codigo);
ALTER TABLE reservas ADD CONSTRAINT FK_RESERVA2
FOREIGN KEY (libro) REFERENCES libros(codigo);

/*CRUD prestamo*/

ALTER TABLE prestamos ADD CONSTRAINT FK_PRESTAMO1
FOREIGN KEY (afiliado) REFERENCES afiliados(codigo)
ON DELETE SET NULL;
ALTER TABLE prestamos ADD CONSTRAINT FK_PRESTAMO2
FOREIGN KEY (libro) REFERENCES libros(codigo)
ON DELETE CASCADE;
ALTER TABLE prestamos ADD CONSTRAINT FK_PRESTAMO3
FOREIGN KEY (empleadoReg) REFERENCES bibliotecarios(empleado)
ON DELETE SET NULL;
ALTER TABLE prestamos ADD CONSTRAINT FK_PRESTAMO4
FOREIGN KEY (empleadoEnt) REFERENCES bibliotecarios(empleado)
ON DELETE SET NULL;

/*CRUD multa*/

ALTER TABLE multas ADD CONSTRAINT PK_MULTA
PRIMARY KEY (causa, prestamo);
ALTER TABLE multas ADD CONSTRAINT FK_MULTA1
FOREIGN KEY (prestamo) REFERENCES prestamos(codigo);
ALTER TABLE multas ADD CONSTRAINT FK_MULTA2
FOREIGN KEY (causa) REFERENCES causas(id);
                   
/*Ciclo 2*/
ALTER TABLE reservasSalones ADD CONSTRAINT PK_RESERVASSALONES
PRIMARY KEY (codigo);
ALTER TABLE salones ADD CONSTRAINT PK_SALONES
PRIMARY KEY (numero, biblioteca);
ALTER TABLE tiposSalones ADD CONSTRAINT PK_TIPOSSALONES
PRIMARY KEY (tipo);
ALTER TABLE reservasSalones ADD CONSTRAINT FK_RESERVASSALONES1
FOREIGN KEY (salonNum, salonBib) REFERENCES salones(numero, biblioteca);
ALTER TABLE reservasSalones ADD CONSTRAINT FK_RESERVASSALONES2
FOREIGN KEY (afiliado) REFERENCES afiliados(codigo);
ALTER TABLE reservasSalones ADD CONSTRAINT FK_RESERVASSALONES3
FOREIGN KEY (bibliotecario) REFERENCES bibliotecarios(empleado);
ALTER TABLE salones ADD CONSTRAINT FK_SALONES1
FOREIGN KEY (tipo) REFERENCES tiposSalones(tipo);
ALTER TABLE salones ADD CONSTRAINT FK_SALONES2
FOREIGN KEY (biblioteca) REFERENCES bibliotecas(nombre);
