
/**GRANT EXECUTE 
ON PA_ TO BD2148825;

REVOKE ALL ON PA_ FROM BD2148825;*/

CREATE ROLE AFILIADO;
CREATE ROLE BIBLIOTECARIO;
CREATE ROLE ARCHIVISTA;
GRANT AFILIADO TO BD2155486;
GRANT AFILIADO TO BD2155609;

/*GRANT EXECUTE ON PA_ TO INSTA_PERFIL;*

DROP ROLE INSTA_PERFIL;