CREATE VIEW BLOQUEADOS AS 
SELECT CODIGO,NOMBRE,CORREO,CEDULA,TELEFONO FROM AFILIADOS WHERE bloqueado=1;

CREATE VIEW AFILIADOS_TIPOS AS 
SELECT CODIGO,NOMBRE,TIPO FROM AFILIADOS;

/*Libros*/
CREATE VIEW POPULARIDAD AS
SELECT LIBRO, COUNT(CODIGO) AS NUMERO_DE_PRESTAMOS FROM PRESTAMOS
GROUP BY LIBRO;

DROP VIEW BLOQUEADOS;
DROP VIEW AFILIADOS_TIPOS;
DROP VIEW POPULARIDAD;